### ISSUE TITLE
Give Matt write access

### ISSUE THREAD

**Issue by MKLau** [ProvTools/encapsulator#33]
Currently I'm on read only.

**Comment by tfjmp** [comment]
You already have write access. I think it has been like this from the start.

Michael, Chris and Margo if she accepts the invite have write access.

I think you are trying to push on master which is a protected branch. You should create a pull request to be merged instead.

**Comment by MKLau** [comment]
Hmm, I trying to push to dev and couldn't. I checked the branch protection, and it looks as though nothing is protected. 

My settings for access wasn't listed, but now that I think about it, it could be because I'm an admin. 

The error I'm actually getting is on 'git commit':

'error: gpg failed to sign data'
'fatal: failed to write commit object'

**Comment by MKLau** [comment]
Ah, actually master us protected.

**Comment by MKLau** [comment]
I'll try and clone a fresh copy of the repo and see if that fixes it.

**Comment by MKLau** [comment]
That fixed it.
